openapi: 3.0.3
info:
  title: Nomod API Documentation (latest)
  version: 1.0.0
  description: Nomod API OpenApi Specification
paths:
  /v1/currencies:
    get:
      operationId: v1_currencies_list
      description: Fetch all active currencies sorted by popularity and name.
      parameters:
      - name: ordering
        required: false
        in: query
        description: Which field to use when ordering the results.
        schema:
          type: string
      tags:
      - v1
      security:
      - apiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CurrenciesApi'
          description: ''
        '401':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    nullable: false
                    description: Text of the error message.
                    example: Authentication credentials were not provided.
                  code:
                    type: object
                    nullable: false
                    description: Specific error code identifying the error.
                    example: not_authenticated
          description: ''
        '429':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    nullable: false
                    description: Text of the error message.
                    example: Request was throttled. Expected available in 1 second.
                  code:
                    type: object
                    nullable: false
                    description: Specific error code identifying the error.
                    example: throttled
          description: ''
  /v1/link:
    post:
      operationId: Generate Link
      description: Generate link.
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateLinkRequest'
        required: true
      security:
      - apiKeyAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateLinkRequest'
          description: ''
        '400':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    nullable: false
                    description: Text of the error message.
                  code:
                    type: object
                    nullable: true
                    description: Specific error code identifying the error.
          description: ''
  /v1/link/{uuid}:
    get:
      operationId: Retrieve Link
      description: Retrieve link details by UUID.
      parameters:
      - in: path
        name: uuid
        schema:
          type: string
        required: true
      - in: query
        name: uuid
        schema:
          type: string
          format: uuid
        description: UUID of the link
      tags:
      - v1
      security:
      - apiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateLinkRequest'
          description: ''
        '404':
          content:
            application/json:
              schema:
                description: Link not found
          description: ''
  /v1/wcommerce/authenticate:
    get:
      operationId: Woocommerce Authenticate
      description: test out the api key and get business information.
      tags:
      - v1
      security:
      - apiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessApi'
          description: ''
        '401':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    nullable: false
                    description: Text of the error message.
                    example: Authentication credentials were not provided.
                  code:
                    type: object
                    nullable: false
                    description: Specific error code identifying the error.
                    example: not_authenticated
          description: ''
        '429':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    nullable: false
                    description: Text of the error message.
                    example: Request was throttled. Expected available in 1 second.
                  code:
                    type: object
                    nullable: false
                    description: Specific error code identifying the error.
                    example: throttled
          description: ''
  /v1/zapier/authenticate:
    get:
      operationId: Authenticate
      description: test out the api key and get business information.
      tags:
      - v1
      security:
      - apiKeyAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BusinessApi'
          description: ''
        '401':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    nullable: false
                    description: Text of the error message.
                    example: Authentication credentials were not provided.
                  code:
                    type: object
                    nullable: false
                    description: Specific error code identifying the error.
                    example: not_authenticated
          description: ''
        '429':
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    nullable: false
                    description: Text of the error message.
                    example: Request was throttled. Expected available in 1 second.
                  code:
                    type: object
                    nullable: false
                    description: Specific error code identifying the error.
                    example: throttled
          description: ''
components:
  schemas:
    BusinessApi:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          readOnly: true
        name:
          type: string
          readOnly: true
        status:
          allOf:
          - $ref: '#/components/schemas/StatusEnum'
          readOnly: true
        image:
          type: string
          format: uri
          readOnly: true
          title: Business image
      required:
      - image
      - name
      - status
      - uuid
    CreateLinkRequest:
      type: object
      properties:
        title:
          type: string
          description: Title of the link.
          maxLength: 100
        currency:
          type: string
          description: Currency code. Get the currency code form /currencies api
          maxLength: 3
        discount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          default: '0.00'
          description: Discount amount to be added
        discount_percentage:
          type: integer
          default: 0
          description: Discount percentage.
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
          description: Total amount.
        note:
          type: string
          nullable: true
          description: Optional note for the link.
        allow_tip:
          type: boolean
          default: false
          description: Allow tips.
        shipping_address_required:
          type: boolean
          default: false
          description: Whether shipping address is required.
        items:
          type: array
          items:
            $ref: '#/components/schemas/LinkItem'
          description: List of items with name and amount.
        customFields:
          type: array
          items:
            $ref: '#/components/schemas/LinkCustomField'
          nullable: true
          description: 'Custom fields to add. Note: max you can add 5'
      required:
      - amount
      - currency
      - items
      - title
    CurrenciesApi:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          description: Unique Identifier of the Currency.
        name:
          type: string
          description: Name of the Currency
        code:
          type: string
          description: Currency code
        decimal_places:
          type: integer
          description: Number of decimal places for the currency.
        denominations:
          type: array
          items:
            type: string
          description: List of available denominations based on the currency code
          readOnly: true
      required:
      - code
      - decimal_places
      - denominations
      - name
      - uuid
    LinkCustomField:
      type: object
      properties:
        name:
          type: string
        is_required:
          type: boolean
          default: false
      required:
      - name
    LinkItem:
      type: object
      properties:
        name:
          type: string
        amount:
          type: string
          format: decimal
          pattern: ^-?\d{0,8}(?:\.\d{0,2})?$
      required:
      - amount
      - name
    StatusEnum:
      enum:
      - limited
      - enabled
      - review
      - disabled
      type: string
      description: |-
        * `limited` - Limited
        * `enabled` - Enabled
        * `review` - Review
        * `disabled` - Disabled
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
      description: Your API key. This is required by all endpoints to access our API
        programatically.                             You can view your API Key by
        navigating to the app settings
